#!/bin/bash
if [ -n "$1" ] ; then
    DATAPATH="$1"
else
    echo -n "Enter data path: "
    read DATAPATH
fi
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run -it \
        --name="cartogapoint_labeler" \
        --volume=$XSOCK:$XSOCK:rw \
        --volume=$XAUTH:$XAUTH:rw \
        -v $DATAPATH:/dataset \
        --env="XAUTHORITY=${XAUTH}" \
        --env="DISPLAY" \
        --env="UID=`id -u $who`" \
        --env="UID=`id -g $who`" \
        --gpus all \
    pj/point_labeler \
    bash

